### ISSUE TITLE
v3.0.1 installation fails, possibly due to mismatch between module name a folder/zip name  

### ISSUE THREAD

**Issue by i-s-o** [NationalSecurityAgency/qgis-datetimetools-plugin#1]
I received the following message when I installed the new version of the plugin:
```
2021-01-30T12:26:11     CRITICAL    Traceback (most recent call last):
              File "C:/tools/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
              __import__(packageName)
              File "C:/tools/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'qgis-datetimetools-plugin-3'
```

Here are the contents of the initial and the new version of the downloadable zip files:

|version | downloaded file | contents (folder name)|
|---|---|---|
|3.0.0 | datetimetools-3.0.0.zip | datetimetools|
|3.0.1 | qgis-datetimetools-plugin-3.0.1.zip | qgis-datetimetools-plugin-3.0.1|

I was able to install it after renaming the contents of the zip file to `datetimetools`.

**Comment by hamiltoncj** [comment]
Thanks for letting me know. I forgot to include the zipped file prepared for installation into QGIS. It is now available.  What was there was just the master set of code, but what you did is a proper fix although there will be some unnecessary files.
